### PR TITLE
Palloquin patch 2

### PR DESCRIPTION
**Pull request by DaafSamson**
added setting allowManualDefault

when set to false the user can not select the 'default' or 'empty' setting anymore once set.

### CODE REVIEW

**Comment by EdouardTack** [comment]
Hello Palloquin,
can you just add a class when the allowManualDefault is set to false.
in line ~215, method wrapElement(), you can name the class "candlestick-default-disabled"

And i see an other thing, ~line 115, in switch case 'default', when allowManualDefault is set to false, you have to disable the reset action.
Ex (I do not test)

``` javascript
var candlestick = candlestickLightInitialize($(this), defaults);
if (defaults.allowManualDefault) {
    candlestick.defaultOrganization();
    candlestick.setValue(0);
}
```

And can you use gulp to minimize the js and add it to commit, thx.

Edouard

**Comment by DaafSamson** [comment]
Hi Edouard,

Added the steps requested, just not sure how to gulp something..

**Comment by EdouardTack** [comment]
Palloquin,
You know [gulpjs ](http://gulpjs.com/) ?

If you don't, you have to install it and update to load librairies i use

``` ssh
npm install --global gulp-cli
npm update
```

and to launch the minimize

``` ssh
gulp
```

if not a success, i will do.
I'm checking your code.

Edouard

**Comment by DaafSamson** [comment]
Hi, No I don't know glubjs. Nor do I use npm... I just edited the file on the GitHub site without using any local client.
Thanks!

**Comment by EdouardTack** [comment]
Ok, i will do it.
I will merge your pull request later tonight.
Thanks for contribution

**Pull request merged**
